# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: buoy.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'buoy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbuoy.proto\x12\x07\x62uoy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"M\n\x06Sensor\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.buoy.v1.SensorStatus\x12\x0f\n\x07samples\x18\x03 \x01(\r\"\x8b\x03\n\x0bObservation\x12\x16\n\x0eobservation_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x62uoy_id\x18\x02 \x01(\t\x12/\n\x0brecorded_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\x08position\x18\x04 \x01(\x0b\x32\x11.buoy.v1.Position\x12\x1a\n\rwave_height_m\x18\x05 \x01(\x01H\x00\x88\x01\x01\x12\x19\n\x0cwater_temp_c\x18\x06 \x01(\x01H\x01\x88\x01\x01\x12\x19\n\x0cwind_gust_ms\x18\x07 \x01(\x01H\x02\x88\x01\x01\x12\x16\n\tbattery_v\x18\x08 \x01(\x01H\x03\x88\x01\x01\x12\x11\n\tqc_passed\x18\t \x01(\x08\x12\x12\n\x05notes\x18\n \x01(\tH\x04\x88\x01\x01\x12 \n\x07sensors\x18\x0b \x03(\x0b\x32\x0f.buoy.v1.SensorB\x10\n\x0e_wave_height_mB\x0f\n\r_water_temp_cB\x0f\n\r_wind_gust_msB\x0c\n\n_battery_vB\x08\n\x06_notes\"3\n\x05\x42\x61tch\x12*\n\x0cobservations\x18\x01 \x03(\x0b\x32\x14.buoy.v1.Observation*z\n\x0cSensorStatus\x12\x1d\n\x19SENSOR_STATUS_UNSPECIFIED\x10\x00\x12\x14\n\x10SENSOR_STATUS_OK\x10\x01\x12\x1a\n\x16SENSOR_STATUS_DEGRADED\x10\x02\x12\x19\n\x15SENSOR_STATUS_OFFLINE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buoy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORSTATUS']._serialized_start=624
  _globals['_SENSORSTATUS']._serialized_end=746
  _globals['_POSITION']._serialized_start=56
  _globals['_POSITION']._serialized_end=92
  _globals['_SENSOR']._serialized_start=94
  _globals['_SENSOR']._serialized_end=171
  _globals['_OBSERVATION']._serialized_start=174
  _globals['_OBSERVATION']._serialized_end=569
  _globals['_BATCH']._serialized_start=571
  _globals['_BATCH']._serialized_end=622
# @@protoc_insertion_point(module_scope)
